<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\Interfaces\Services\" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\domain\domain.csproj" />
  </ItemGroup>

</Project>
